### ISSUE TITLE
Google Container

### ISSUE THREAD

**Issue by wefalltomorrow** [spa5k/Unbuttun#1]
What happened to this extension? https://github.com/Unbuttun/firefox-google-container

**Comment by spa5k** [comment]
@wefalltomorrow there was some problems with it plus it was sort of 70% ported, few long time taking things were left to be done, i did not had enough time. So i stopped and deleted the repo

**Comment by wefalltomorrow** [comment]
> @wefalltomorrow there was some problems with it plus it was sort of 70% ported, few long time taking things were left to be done, i did not had enough time. So i stopped and deleted the repo

Fair enough :)
